# M2 MacBook için optimize edilmiş konfigürasyon
# 8GB RAM için memory-efficient ayarlar

model:
  sam_model_type: "vit_b"  # En küçük SAM modeli
  sam_checkpoint_path: null
  clip_model_name: "openai/clip-vit-base-patch32"
  device: "mps"  # M2 için MPS kullan
  enable_caching: true
  cache_dir: "model_cache"

processing:
  similarity_threshold: 45.0  # Çok daha düşük threshold
  luggage_detection_threshold: 0.3  # Çok düşük threshold
  batch_size: 1  # Tek resim işle
  max_image_size: 1024  # Daha küçük resim boyutu
  enable_segmentation: true
  enable_feature_analysis: true
  enable_geometric_verification: true
  enable_ensemble_voting: true

logging:
  level: "INFO"
  log_file: null
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  enable_file_logging: false
  max_log_size_mb: 5
  backup_count: 2

cache:
  max_age_days: 7  # Daha kısa cache süresi
  max_size_gb: 2.0  # Daha küçük cache
  auto_cleanup: true
  cleanup_interval_hours: 12

output:
  default_output_dir: "output"
  create_detailed_reports: true
  create_summary_reports: true
  save_similarity_matrix: false  # Memory tasarrufu
  save_processed_images: false
  archive_old_results: true
  archive_age_days: 3 